### ISSUE TITLE
need a read me file

### ISSUE THREAD

**Issue by iTaipei** [linmstrue/myTest#2]
need a read me file

**Comment by linmstrue** [comment]
wait 2 days

**Comment by iTaipei** [comment]
Need title , body , and footer.

**Comment by linmstrue** [comment]
ok! like this file?
[README.txt](https://github.com/linmstrue/myTest/files/225447/README.txt)

**Comment by iTaipei** [comment]
yes!!

**Comment by iTaipei** [comment]
have a question

**Comment by linmstrue** [comment]
ok
